all: MyCompress.cpp MyDecompress.cpp ForCompress.cpp PipeCompress.cpp ParFork.cpp MiniShell.cpp MoreShell.cpp DupShell.cpp ParThread.cpp
g++ -o MyCompress MyCompress.cpp
g++ -o MyDecompress MyDecompress.cpp
g++ -o ForkCompress ForCompress.cpp
g++ -o PipeCompress PipeCompress.cpp
g++ -o ParFork ParFork.cpp
g++ -o MiniShell MiniShell.cpp
g++ -o MoreShell MoreShell.cpp
g++ -o DupShell DupShell.cpp
g++ -o ParThread ParThread.cpp -lpthread
