all: MyCompress.cpp MyDecompress.cpp ForkCompress.cpp PipeCompress.cpp ParFork.cpp MinShell.cpp MoreShell.cpp DupShell.cpp ParThread.cpp
	g++ MyCompress.cpp -o MyCompress
	g++ MyDecompress.cpp -o MyDecompress
	g++ ForkCompress.cpp -o ForkCompress
	g++ PipeCompress.cpp -o PipeCompress
	g++ ParFork.cpp -o ParFork
	g++ MinShell.cpp -o MiniShell
	g++ MoreShell.cpp -o MoreShell
	g++ DupShell.cpp -o DupShell
	g++ -o ParThread ParThread.cpp -lpthread