all: p1server.cpp p1client.cpp p2server.cpp p2client.cpp p3server.cpp p3client.cpp
	g++ -o p1server p1server.cpp -lpthread
	g++ p1client.cpp -o p1client
	g++ -o p2server p2server.cpp -lpthread
	g++ p2client.cpp -o p2client
	g++ -o p3server p3server.cpp -lpthread
	g++ p3client.cpp -o p3client

